# Generated by Django 5.0 on 2024-08-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tailoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_type', models.CharField(choices=[('shirt', 'Shirt'), ('paint', 'Paint'), ('kurta', 'Kurta Pajama')], default='shirt', max_length=100, verbose_name='Clothing Type')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('shirt_length', models.FloatField(blank=True, null=True, verbose_name='Shirt Length')),
                ('shirt_shoulder', models.FloatField(blank=True, null=True, verbose_name='Shirt Shoulder')),
                ('shirt_full_chest', models.FloatField(blank=True, null=True, verbose_name='Shirt Full Chest')),
                ('shirt_full_stomach', models.FloatField(blank=True, null=True, verbose_name='Shirt Full Stomach')),
                ('shirt_full_hip', models.FloatField(blank=True, null=True, verbose_name='Shirt Full Hip')),
                ('shirt_hands', models.FloatField(blank=True, null=True, verbose_name='Shirt Hands')),
                ('shirt_full_arms', models.FloatField(blank=True, null=True, verbose_name='Shirt Full Arms')),
                ('shirt_cuff', models.FloatField(blank=True, null=True, verbose_name='Shirt Cuff')),
                ('shirt_collor', models.FloatField(blank=True, null=True, verbose_name='Shirt Collar')),
                ('paint_length', models.FloatField(blank=True, null=True, verbose_name='Paint Length')),
                ('paint_waist', models.FloatField(blank=True, null=True, verbose_name='Paint Waist')),
                ('paint_hip', models.FloatField(blank=True, null=True, verbose_name='Paint Hip')),
                ('paint_full_thighs', models.FloatField(blank=True, null=True, verbose_name='Paint Full Thighs')),
                ('paint_full_knees', models.FloatField(blank=True, null=True, verbose_name='Paint Full Knees')),
                ('paint_leg_bottom', models.FloatField(blank=True, null=True, verbose_name='Paint Leg Bottom')),
                ('paint_full_seat', models.FloatField(blank=True, null=True, verbose_name='Paint Full Seat')),
                ('kurta_length', models.FloatField(blank=True, null=True, verbose_name='Kurta Length')),
                ('kurta_shoulder', models.FloatField(blank=True, null=True, verbose_name='Kurta Shoulder')),
                ('kurta_full_chest', models.FloatField(blank=True, null=True, verbose_name='Kurta Full Chest')),
                ('kurta_full_stomach', models.FloatField(blank=True, null=True, verbose_name='Kurta Full Stomach')),
                ('kurta_full_hip', models.FloatField(blank=True, null=True, verbose_name='Kurta Full Hip')),
                ('kurta_hands', models.FloatField(blank=True, null=True, verbose_name='Kurta Hands')),
                ('kurta_full_arms', models.FloatField(blank=True, null=True, verbose_name='Kurta Full Arms')),
                ('kurta_cuff', models.FloatField(blank=True, null=True, verbose_name='Kurta Cuff')),
                ('kurta_collor', models.FloatField(blank=True, null=True, verbose_name='Kurta Collar')),
                ('pajama_length', models.FloatField(blank=True, null=True, verbose_name='Pajama Length')),
                ('pajama_leg_bottom', models.FloatField(blank=True, null=True, verbose_name='Pajama Leg Bottom')),
                ('pajama_waist', models.FloatField(blank=True, null=True, verbose_name='Pajama Waist')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
