# Generated by Django 5.0 on 2024-08-04 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoring',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Order Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tailoring',
            name='order_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Order Time'),
            preserve_default=False,
        ),
    ]
