# Generated by Django 5.0 on 2024-08-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_tailoring_order_date_tailoring_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoring',
            name='bill',
            field=models.CharField(default='unpaid', max_length=255),
        ),
    ]
