# Generated by Django 5.0 on 2024-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0003_tailoring_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoring',
            name='email',
            field=models.EmailField(default='Null', max_length=254),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='bill',
            field=models.CharField(default='unpaid', max_length=15),
        ),
    ]
