# Generated by Django 5.0 on 2024-08-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_tailoring_email_alter_tailoring_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailoring',
            name='age',
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_full_knees',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Full Knees'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_full_seat',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Full Seat'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_full_thighs',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Full Thighs'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_hip',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Hip'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_leg_bottom',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Leg Bottom'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Length'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_waist',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Waist'),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='clothing_type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('shirt_pant', 'Shirt and Pant'), ('kurta', 'Kurta'), ('kurta_pajama', 'Kurta Pajama'), ('kurta_puna_pant', 'Kurta Puna Pant'), ('puna_pant', 'Puna Pant'), ('pajama', 'Pajama')], default='shirt', max_length=100, verbose_name='Clothing Type'),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='paint_full_knees',
            field=models.FloatField(blank=True, null=True, verbose_name='Pant Full Knees'),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='paint_full_seat',
            field=models.FloatField(blank=True, null=True, verbose_name='Pant Full Seat'),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='paint_full_thighs',
            field=models.FloatField(blank=True, null=True, verbose_name='Pant Full Thighs'),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='paint_hip',
            field=models.FloatField(blank=True, null=True, verbose_name='Pant Hip'),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='paint_leg_bottom',
            field=models.FloatField(blank=True, null=True, verbose_name='Pant Leg Bottom'),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='paint_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Pant Length'),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='paint_waist',
            field=models.FloatField(blank=True, null=True, verbose_name='Pant Waist'),
        ),
    ]
