# Generated by Django 5.0 on 2024-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_remove_tailoring_age_tailoring_puna_pant_full_knees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailoring',
            name='puna_pant_full_knees',
        ),
        migrations.RemoveField(
            model_name='tailoring',
            name='puna_pant_full_seat',
        ),
        migrations.RemoveField(
            model_name='tailoring',
            name='puna_pant_full_thighs',
        ),
        migrations.RemoveField(
            model_name='tailoring',
            name='puna_pant_hip',
        ),
        migrations.RemoveField(
            model_name='tailoring',
            name='puna_pant_leg_bottom',
        ),
        migrations.RemoveField(
            model_name='tailoring',
            name='puna_pant_length',
        ),
        migrations.RemoveField(
            model_name='tailoring',
            name='puna_pant_waist',
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='clothing_type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('paint', 'Pant'), ('shirt_pant', 'Shirt and Pant'), ('kurta_pajama', 'Kurta Pajama'), ('kurta_puna_pant', 'Kurta Puna Pant'), ('puna_pant', 'Puna Pant'), ('pajama', 'Pajama')], default='shirt', max_length=100, verbose_name='Clothing Type'),
        ),
    ]
