# Generated by Django 5.0 on 2024-08-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0006_remove_tailoring_puna_pant_full_knees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_full_knees',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Full Knees'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_full_seat',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Full Seat'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_full_thighs',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Full Thighs'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_hip',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Hip'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_leg_bottom',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Leg Bottom'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Length'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='puna_pant_waist',
            field=models.FloatField(blank=True, null=True, verbose_name='Puna Pant Waist'),
        ),
    ]
