# Generated by Django 5.0 on 2024-08-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
        migrations.AddField(
            model_name='tailoring',
            name='bill_number',
            field=models.CharField(default=0, max_length=5, unique=True, verbose_name='Bill Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='clothing_type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('paint', 'Pant'), ('kurta', 'Kurta'), ('puna_pant', 'Puna Pant'), ('pajama', 'Pajama'), ('shirt_pant', 'Shirt and Pant'), ('kurta_pajama', 'Kurta Pajama'), ('kurta_puna_pant', 'Kurta Puna Pant')], default='shirt', max_length=100, verbose_name='Clothing Type'),
        ),
    ]
