# Generated by Django 5.0 on 2024-08-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0009_delete_details_tailoring_bill_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailoring',
            name='bill_number',
        ),
    ]
