# Generated by Django 5.0 on 2024-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_remove_tailoring_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoring',
            name='bill_number',
            field=models.CharField(default=0, editable=False, max_length=5, unique=True, verbose_name='Bill Number'),
            preserve_default=False,
        ),
    ]
