# Generated by Django 5.0 on 2024-08-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0012_billnumbersequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillNumberSequence',
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='bill_number',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
    ]
