# Generated by Django 5.0 on 2024-08-11 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0013_delete_billnumbersequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailoring',
            name='bill_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=5, unique=True, verbose_name='Bill Number'),
        ),
    ]
