# Generated by Django 5.0 on 2024-08-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0014_alter_tailoring_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailoring',
            name='bill',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10),
        ),
    ]
