# Generated by Django 5.0 on 2024-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0015_alter_tailoring_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoring',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tailoring',
            name='bill',
            field=models.CharField(default='unpaid', max_length=15),
        ),
    ]
