# Generated by Django 5.0 on 2024-08-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0016_tailoring_advance_amount_alter_tailoring_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailoring',
            name='bill_number',
            field=models.IntegerField(),
        ),
    ]
