# Generated by Django 5.0 on 2024-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0017_alter_tailoring_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1, unique=True)),
            ],
            options={
                'verbose_name': 'Bill Number Sequence',
                'verbose_name_plural': 'Bill Number Sequences',
            },
        ),
    ]
