# Generated by Django 5.0 on 2025-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0018_billnumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoring',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
